name: Genera ZIP per deploy manuale

on:
  push:
    branches:
      - main

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice sorgente
        uses: actions/checkout@v3

      - name: Crea archivio ZIP
        run: zip -r Gestionale25.zip . -x ".git/*" ".github/*" "README.md"

      - name: Salva ZIP come artefatto
        uses: actions/upload-artifact@v4
        with:
          name: Gestionale25
          path: Gestionale25.zip
